---
layout: cv
title: Eby's CV
---
# 
Physicist, Mathematician, Cambridge professor.

<div id="webaddress">
<a href="isaac@applesdof>isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>all.org"


N’Da Germain Eby Bassa
(435) 314-9053 | bas24028@byui.edu | Rexburg, ID | www.linkedin.com/in/eby-bassa 
# EDUCATION
Brigham Young University – Idaho	Rexburg, ID   
Bachelor of Science in Accounting, Minor in Business Analytics             Expected Graduation: July 2026	
Snow College                                                                                                                          Ephraim, UT                                                                                                    
Associate of Science in Accounting | GPA: 3.98                                                         Jan 2023 – May 2024
Institut National Polytechnique Félix Houphouët-Boigny (INPHB)	Yamoussoukro, Ivory Coast
License Degree in Finance and Accounting				   		   Sep 2014 – Jul 2017
# EXPERIENCE
Eagle Eye Produce	Idaho Falls, ID
Accounting Intern	Apr 2025 – Sep 2025  
•	Prepared and analyzed 100+ general ledger entries monthly, ensuring 100% compliance with GAAP and improving reporting accuracy, reducing post-close corrections by 15%
•	Performed monthly close process by completing account reconciliations and journal entries, shortening month-end close time from 4 days to 3 days
•	Coded invoices, set up new accounts, and executed special projects involving financial data analysis and research
•	Executed and optimized monthly financial tracking and variance reporting, providing timely insights enabling managerial decisions 20% faster and keeping spending within targets
Brigham Young University – Idaho                                                                                      Rexburg, ID
French Conversation Lab Tutor (Volunteer)                                                         	 Jan 2025 – Apr 2025
•	Led weekly French sessions for beginner to advanced students, improving fluency and comprehension
•	Designed tailored lesson plans, helping 80% of participants improve oral proficiency
•	Tracked progress and provided feedback, enabling 90% of students to meet semester goals
Olam Agri Rubber CI	Aniassue, Ivory Coast
Junior Accountant	Jul 2020 – Dec 2022
•	Analyzed monthly vendor schedules, ensuring 100% compliance with internal financial controls
•	Prepared and reviewed provisions journal entries each month, elevating statement accuracy and decreasing adjustments by 15%
•	Communicated with vendors to reconcile account discrepancies within 48 hours, maintaining supplier satisfaction and decreasing payment delays by 20%
# LEADERSHIP & SERVICE
The Church of Jesus Christ of Latter-day Saints	Monrovia, Liberia
Volunteer Representative 	Mar 2018 – Mar 2020
•	Planned and facilitated weekly training sessions for 35 representatives, improving team performance 
•	Managed reimbursements and maintained detailed financial records with 100% accuracy, ensuring transparency and compliance with organizational policies
# SKILLS & INTEREST
•	Technical Skills: Excel, Word, PowerPoint, SQL, Drake Tax, Business Central, FAMOUS
•	Languages: English (fluent), French (native)    
•	Active member of the Student Accounting Society (SAS)                                            
# CERTIFICATE
•	Data Science Certificate (In Progress)



<!-- ### Footer

Last updated: May 2013 -->